apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::062730415246:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::062730415246:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-27T19:39:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1645"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0a51d008-1af0-4ec7-81fc-f8acd36bf4b2
